apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
  labels:
    {{- include "vmware-cluster.labels" . | nindent 4 }}
spec:
  cloudCredentialSecretName: {{ .Values.vmwareCredentials.namespace }}:{{ include "vmware-cluster.vsphereCredentalName" . }}
  kubernetesVersion: {{ .Values.cluster.rke2Version }}
  {{- if .Values.cluster.localClusterAuthEndpoint.enabled }}
  localClusterAuthEndpoint:
    caCerts: {{ .Values.cluster.localClusterAuthEndpoint.caCerts }}
    enabled: {{ .Values.cluster.localClusterAuthEndpoint.enabled }}
    fqdn: {{ .Values.cluster.localClusterAuthEndpoint.fqdn }}
  {{- end }}
  defaultPodSecurityPolicyTemplateName: {{ .Values.cluster.defaultPodSecurityPolicyTemplateName }}
  enableNetworkPolicy: {{ .Values.cluster.enableNetworkPolicy }}
  rkeConfig:
    # Add Adational Manifests
    chartValues:
      {{ toYaml .Values.cluster.chartValues | nindent 6 }}
    {{- if not .Values.cluster.etcd.disableSnapshots }}
    etcd:
      {{ toYaml .Values.cluster.etcd | nindent 6 }}
      {{- if .Values.cluster.enableS3EtcdSnapshots }}
      s3:
        {{ toYaml .Values.cluster.s3 | nindent 8 }}
      {{- end }}
    {{- end }}
    machineGlobalConfig:
      {{ toYaml .Values.cluster.machineGlobalConfig | nindent 6 }}
    machinePools:
      {{- if .Values.enableServer }}
      {{- toYaml .Values.cluster.serverPool | nindent 6 }}
        quantity: {{ .Values.serverVmConfig.quantity}}
        machineConfigRef:
          kind: VmwarevsphereConfig
          name: {{ include "vmware-cluster.serverPoolName" . }}
      {{- end }}
      {{- if .Values.enableAgent }}
      {{- toYaml .Values.cluster.agentPool | nindent 6 }}
        quantity: {{ .Values.agentVmConfig.quantity}}
        machineConfigRef:
          kind: VmwarevsphereConfig
          name: {{ include "vmware-cluster.agentPoolName" . }}
      {{- end }}
    machineSelectorConfig:
      {{- toYaml .Values.cluster.machineSelectorConfig | nindent 6 }}
    registries: 
      {{ toYaml .Values.cluster.registries | nindent 6 }}
    upgradeStrategy:
      {{ toYaml .Values.cluster.upgradeStrategy | nindent 6 }}
    
    additionalManifest: |-
      # Extra Yaml
      {{- if .Values.bootstrapFlux }}
      {{ ( include "vmware-cluster.flux" . ) | nindent 6 }}
      ---
      # define flux-system sync
      apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        interval: 1m0s
        ref:
          branch: main
        secretRef:
          name: flux-system
        url: {{  .Values.fluxSystemGit }}
      ---
      apiVersion: v1
      data:
        identity: {{ .Values.identity | b64enc  }}
        identity.pub: {{ .Values.identitypub | b64enc  }}
      kind: Secret
      metadata:
        name: flux-system
        namespace: flux-system
      type: Opaque
      ---
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: flux-system
        namespace: flux-system
      spec:
        interval: 10m0s
        path: {{  .Values.fluxSystemPath }}
        prune: true
        sourceRef:
          kind: GitRepository
          name: flux-system
      {{- end }}
      # add flux sync