apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.namespace }}
  labels:
    {{- include "vmware-cluster.labels" . | nindent 4 }}
spec:
  cloudCredentialSecretName: {{ .Values.vmwareCredentials.namespace }}:{{ include "vmware-cluster.vsphereCredentalName" . }}
  kubernetesVersion: {{ .Values.cluster.rke2Version }}
  {{- if .Values.cluster.localClusterAuthEndpoint.enabled }}
  localClusterAuthEndpoint:
    caCerts: {{ .Values.cluster.localClusterAuthEndpoint.caCerts }}
    enabled: {{ .Values.cluster.localClusterAuthEndpoint.enabled }}
    fqdn: {{ .Values.cluster.localClusterAuthEndpoint.fqdn }}
  {{- end }}
  defaultPodSecurityPolicyTemplateName: {{ .Values.cluster.defaultPodSecurityPolicyTemplateName }}
  enableNetworkPolicy: {{ .Values.cluster.enableNetworkPolicy }}
  rkeConfig:
    chartValues:
      {{ toYaml .Values.cluster.chartValues | nindent 6 }}
    {{- if not .Values.cluster.etcd.disableSnapshots }}
    etcd:
      {{ toYaml .Values.cluster.etcd | nindent 6 }}
      {{- if .Values.cluster.enableS3EtcdSnapshots }}
      s3:
        {{ toYaml .Values.cluster.s3 | nindent 8 }}
      {{- end }}
    {{- end }}
    machineGlobalConfig:
      {{ toYaml .Values.cluster.machineGlobalConfig | nindent 6 }}
    machinePools:
      {{- if .Values.enableServer }}
      {{- toYaml .Values.cluster.serverPool | nindent 6 }}
        quantity: {{ .Values.serverVmConfig.quantity}}
        machineConfigRef:
          kind: VmwarevsphereConfig
          name: {{ include "vmware-cluster.serverPoolName" . }}
      {{- end }}
      {{- if .Values.enableAgent }}
      {{- toYaml .Values.cluster.agentPool | nindent 6 }}
        quantity: {{ .Values.agentVmConfig.quantity}}
        machineConfigRef:
          kind: VmwarevsphereConfig
          name: {{ include "vmware-cluster.agentPoolName" . }}
      {{- end }}
    machineSelectorConfig:
      {{- toYaml .Values.cluster.machineSelectorConfig | nindent 6 }}
    registries: 
      {{ toYaml .Values.cluster.registries | nindent 6 }}
    upgradeStrategy:
      {{ toYaml .Values.cluster.upgradeStrategy | nindent 6 }}