apiVersion: v1
data:
  vmwarevspherecredentialConfig-password: {{ toString .Values.vmwareCredentials.password | b64enc  }}
  vmwarevspherecredentialConfig-username: {{ toString .Values.vmwareCredentials.username | b64enc  }}
  vmwarevspherecredentialConfig-vcenter: {{ toString  .Values.vmwareCredentials.host | b64enc  }}
  vmwarevspherecredentialConfig-vcenterPort: {{ toString  .Values.vmwareCredentials.port | b64enc  }}
kind: Secret
metadata:
  labels:
    {{- include "vmware-cluster.labels" . | nindent 4 }}
  annotations:
    field.cattle.io/name: {{ include "vmware-cluster.vsphereCredentalName" . }}
  name: {{ include "vmware-cluster.vsphereCredentalName" . }}
  namespace: {{ .Values.vmwareCredentials.namespace }}
type: Opaque